### ISSUE TITLE
Task: set up a raw Python application that integrates with the Postgres database

### ISSUE THREAD

**Issue by excalliburbd** [the-neighborhood/snapcart-clone#2]
The Consumer part of the application stack is going to be responsible for querying the Database for unprocessed Recipt images then process and structure the data.

As a starting point setup some code that can connect to the database

**Comment by mimijsr09** [comment]
Okay, @excalliburbd  I will start working on it asap!

**Comment by excalliburbd** [comment]
Awesome @mimijsr09 make sure to move the task to In Progress at waffle project

**Comment by mimijsr09** [comment]
@excalliburbd add me as a collaborator please.

**Comment by excalliburbd** [comment]
Ah. My bad. Sent you the link.

**Comment by excalliburbd** [comment]
@mimijsr09 maybe you need to add more commits to be a collaborator. I've done the moving and will do so until new members can do it themselves. Thanks

**Comment by excalliburbd** [comment]
Note: we can use share `images` volume after merging #11 
https://stackoverflow.com/questions/44284484/docker-compose-share-named-volume-between-multiple-containers
